name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Adjust to your target branch

jobs:
  deploy:
    name: Deploy on Self-hosted Runner (s5 with label s10)
    runs-on: [self-hosted, s10]  # s10 is the label assigned to runner s5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update APT and install dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y \
            curl \
            ca-certificates \
            gnupg \
            lsb-release \
            software-properties-common

      - name: Install Docker
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com | sudo sh
          else
            echo "Docker already installed"
          fi

      - name: Install Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose already installed"
          fi

      - name: Stop existing containers (optional)
        run: |
          sudo docker compose -f compose.yml down || true

      - name: Deploy with Docker Compose
        run: |
          sudo docker compose -f compose.yml up -d

